src/apps/support/urls.py
from django.conf import settings
from django.urls import path
from django.views.decorators import csrf

from apps.support import views

urlpatterns = [
    path(f'{settings.ADMIN_PATH}monitor/', csrf.csrf_exempt(views.MonitorView.as_view()), name='monitor'),

    path('v1/blinger/webhook/', csrf.csrf_exempt(views.BlingerWebhookView.as_view()), name='blinger_webhook'),

]

src/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('healthcheck/', include('health_check.urls')),
    path('metrics', include('django_metrics.urls')),
    path(settings.ADMIN_PATH, admin.site.urls),
    path('', include('apps.support.urls')),
]

src/apps/support/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class SupportRequest(models.Model):
    class Meta:
        verbose_name = 'Обращение'
        verbose_name_plural = 'Обращения'

    bot_user_id = models.CharField(max_length=64, verbose_name='ID пользователя в ТГ')
    theme = models.CharField(max_length=16, verbose_name='Контекст обращения')
    mim = models.ForeignKey(User, null=True, blank=True, related_name='support_requests',
                            verbose_name='Ответственный МИМ', on_delete=models.SET_NULL)
    is_done = models.BooleanField(default=False, verbose_name='Обработана ли заявка?')

    def __str__(self):
        return f'Заявка {self.id} от {self.bot_user_id}, тема {self.theme}'


class Message(models.Model):
    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['created_at']

    request = models.ForeignKey(SupportRequest, related_name='messages',
                                verbose_name='Запрос', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    is_auto = models.BooleanField(default=True, verbose_name='Автоматический ответ')
    from_user = models.BooleanField(default=True, verbose_name='Сообщение от пользователя?')
    text = models.TextField(null=True, blank=True, verbose_name='Текст обращения')
    file = CloudinaryField(folder='herb_bot', resource_type='image',
                           null=True, blank=True, verbose_name='Прикреплённый файл')

    def __str__(self):
        return f'Сообщение от {"пользователя" if self.from_user else "техподдержки"}: {self.text}.'


class WarehouseRequest(models.Model):
    class Meta:
        verbose_name = 'Запрос к складу'
        verbose_name_plural = 'Запросы к складу'
        ordering = ['created_at']

    message_id = models.IntegerField(verbose_name='ID сообщения')
    user_id = models.IntegerField(verbose_name='ID клиента, запросившего фото')
    request = models.TextField(verbose_name='Запрос клиента')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')

    def __str__(self):
        return f'Запрос к складу {self.id}.'


class WarehouseResponse(models.Model):
    class Meta:
        verbose_name = 'Ответ склада'
        verbose_name_plural = 'Ответы склада'
        ordering = ['created_at']

    request = models.ForeignKey(
        WarehouseRequest, related_name='responses', verbose_name='Запрос', on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True, verbose_name='Текст обращения')
    file = CloudinaryField(folder='herb_bot', resource_type='image',
                           null=True, blank=True, verbose_name='Прикреплённый файл')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')

    def __str__(self):
        return f'Ответ склада {self.id}.'


class Issue(models.Model):
    class Meta:
        verbose_name = 'Инцидент'
        verbose_name_plural = 'Инциденты'

    user_id = models.IntegerField(verbose_name='ID клиента, создавшего инцидент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')
    title = models.TextField(verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    issue_id = models.CharField(max_length=16, verbose_name='ID задачи')
    is_done = models.BooleanField(default=False, verbose_name='Завершена ли задача?')

    def __str__(self):
        return f'Инцидент {self.issue_id}: {self.title}.'


@receiver(post_save, sender=Message)
def notify_new_message_receiver(sender, instance, created, **kwargs):
    # отправлять уведомление лишь со второго сообщения
    if created and instance.request.messages.count() > 1:
        if not instance.from_user:
            from apps.bot_user.handlers import notify_user
            notify_user(instance)

src/apps/support/forms.py
from datetime import datetime

from atlas_utils.common.exceptions import ValidationError
from django import forms

from utils.datetime import get_now_date_msk, date_format_range, get_four_weeks_from_date


class RangeForm(forms.Form):
    daterange = forms.CharField(required=False)

    def __init__(self, *args, default_start=None, default_end=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.default_start = default_start
        self.default_end = default_end

    def clean_daterange(self):
        daterange = self.cleaned_data['daterange']
        if daterange:
            daterange = daterange.split('-')
            if len(daterange) != 2:
                raise ValidationError('Диапазон указан неверно, должно быть две даты через "-".')
            try:
                for index, date_str in enumerate(daterange):
                    daterange[index] = datetime.strptime(date_str.strip(), date_format_range).date()
            except Exception:
                raise ValidationError('Некорректный формат даты.')
            return daterange
        else:
            if self.default_start and self.default_end:
                return self.default_start, self.default_end
            else:
                today = get_now_date_msk()
                return get_four_weeks_from_date(today)

src/apps/support/views.py
import json

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView

from apps.support.forms import RangeForm
from apps.support.service import SupportService
from utils.datetime import get_now_date_msk, get_four_weeks_from_date, date_format_range
from utils.decorators import error_processing


@method_decorator(error_processing('2.0'), name='dispatch')
class MonitorView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('admin:login')
    redirect_field_name = 'next'
    template_name = 'monitor.html'

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        today = get_now_date_msk()
        date_start, date_end = get_four_weeks_from_date(today)
        form = RangeForm(self.request.GET)
        if form.is_valid():
            date_start, date_end = form.cleaned_data['daterange']
        monitor = SupportService.get_bot_monitor(date_end)
        metrics, date_headers = SupportService.get_warehouse_monitoring(date_start, date_end)
        context['monitor'] = monitor
        context['date_headers'] = date_headers
        context['metrics'] = metrics
        context['daterange'] = f'{date_start.strftime(date_format_range)} - ' \
                               f'{date_end.strftime(date_format_range)}'
        return context


@method_decorator(error_processing('2.0'), name='dispatch')
class BlingerWebhookView(View):

    def post(self, request, *args, **kwargs):
        params = json.loads(request.body)
        channel_id = params['custom_channel_id']
        if channel_id == settings.BLINGER_CHANNEL_ID:
            SupportService.handle_blinger_webhook(params)
        return HttpResponse()

src/apps/support/templates/monitor.html
<!DOCTYPE html>
<html lang="en" class="mdl-js">
<head>
    {% load i18n static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Аналитика бота поддержки</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>

    <style>

        .pointer {
            cursor: pointer;
        }

        .layout-fixed {
            table-layout: fixed;
        }

        .header {
            position: fixed;
            z-index: 1;
            width: 100%;
        }

        #daterange {
            display: inline-block;
            background: #fff;
            cursor: pointer;
            padding: 5px 10px;
            border: 1px solid #ccc;
            vertical-align: middle;
        }

        .container-fluid {
            padding-top: 70px;
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 2;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 60px;
            transition: 0.5s;
        }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        #menu_button {
            width: 23px;
            margin: 5px 20px 5px 0px;
        }

        @media screen and (max-height: 450px) {
            .sidenav {
                padding-top: 15px;
            }

            .sidenav a {
                font-size: 18px;
            }
        }

        @media screen and (max-width: 700px) {
            .layout-fixed {
                table-layout: auto;
            }
        }

    </style>

<body>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'admin:index' %}">Администрирование</a>
    <a href="{% url 'monitor' %}">Аналитика бота поддержки</a>
</div>

<div class="align-items-center bg-white border-bottom d-flex header px-md-4">
    <img id="menu_button" class="pointer" src="{% static "img/menu.png" %}" onclick="openNav()">
    <h5 class="my-0 mr-md-auto">Аналитика бота поддержки</h5>
    <form method="get" id="filter_form">
        {{ form.non_field_errors }}
        <label>Выберите период:</label>
        <div id="daterange">
            <input id="id_daterange" type="text" name="daterange" value="{{ daterange }}" hidden>
            <i class=" fa fa-calendar"></i>&nbsp;<span>{{ daterange }}</span> <i class="fa fa-caret-down"></i>
        </div>
        <button type="submit" class="btn btn-dark ml-3">Ок</button>
    </form>
</div>

<div class="container-fluid">

    <div class="col-12 col-sm-12 col-md-12">
        <h5>Монитор</h5>
        <p>Уникальных посетителей бота: <b>{{ monitor.users }}</b></p>
        <p>Авторизовавшихся пользователей: <b>{{ monitor.auth }}</b></p>
        <p>Не-гербов: <b>{{ monitor.nonherb }}</b></p>
        <p>Сообщений: <b>{{ monitor.msgs }}</b></p>
        <p>Автоматических ответов: <b>{{ monitor.auto_msgs }}</b></p>
        <p>Сообщений от пользователей: <b>{{ monitor.user_msgs }}</b></p>
        <p>Сообщений от менеджеров: <b>{{ monitor.manager_msgs }}</b></p>
    </div>

    <div class="col-12 col-sm-12 col-md-12">
        <h5>Динамика обращений к складу через бота</h5>
        <table class="table layout-fixed">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Метрика</th>
                {% for dh in date_headers %}
                    <th scope="col">{{ dh }}</th>
                {% endfor %}
                <th scope="col">Общее кол-во на конец периода</th>
            </tr>
            </thead>
            <tbody>
            {% for metric_name, data in metrics.items %}
                <tr>
                    <td>{{ metric_name }}</td>
                    {% for d in data %}
                        {% if forloop.last or metric_name == 'Пользователей на неделе' %}
                            <td>{{ d }}</td>
                        {% else %}
                            <td>+{{ d }}</td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="col-12 col-sm-12 col-md-12">
        <h5>Самые популярные пункты меню</h5>
        <table class="table layout-fixed">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Меню</th>
                <th scope="col">Переходов</th>
            </tr>
            </thead>
            <tbody>
            {% for state in monitor.states %}
                <tr>
                    <td>{{ state.0 }}</td>
                    <td>{{ state.1 }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

</div>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

    $(function () {

        moment.locale('ru', {week: {dow: 1}});

        function range_to_str(start, end) {
            let value = start.format('D.MM.YYYY') + ' - ' + end.format('D.MM.YYYY');
            $('#daterange span').html(value);
            $('#daterange input').val(value);
        }

        $('#daterange').daterangepicker({
            minDate: new Date('2020-07-27'),
            ranges: {
                'Прошлый месяц': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                'Текущий месяц': [moment().startOf('month'), moment().endOf('month')],
                'С самого начала': [new Date('2020-07-27'), moment()]
            },
            locale: {
                "customRangeLabel": "Выбрать период",
            },
        }, range_to_str);
        if (!$('#daterange input').val()) {
            let start = moment().subtract(3, 'week').startOf('week');
            let end = moment().endOf('week');
            range_to_str(start, end);
        }

    });
</script>

</body>
</html>